# Generated by Django 4.0.6 on 2022-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_movie_actor_alter_movie_year_delete_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
