name: Django CD
on:
  push:
    branches: [master]
jobs:
  run-test:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Netflix.settings
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
            host: github.com/dilshod1405/Netflix-y.git
            username: dilshod1405
            key: ${{ secrets.KEY }}
            script: |
              git pull
              systemctl restart gunicorn.service