on: [push]
jobs:
  run-test:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: Netflix.settings
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.10
      - name: install Requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
name: Netflix API CI